#define INITIALIZE_SYMBOL   initializePlugin
#define EXECUTE_SYMBOL      executePlugin
#define DEINITIALIZE_SYMBOL deinitializePlugin

#define __MAKE_STR(x) #x
#define _MAKE_STR(x) __MAKE_STR(x)

#define INITIALIZE_SYMBOL_NAME    _MAKE_STR(INITIALIZE_SYMBOL)
#define EXECUTE_SYMBOL_NAME       _MAKE_STR(EXECUTE_SYMBOL)
#define DEINITIALIZE_SYMBOL_NAME  _MAKE_STR(DEINITIALIZE_SYMBOL)

#define INITIALIZE_FUNCTION_SIGNATURE(name) \
  bool name ()
#define EXECUTE_FUNCTION_SIGNATURE(name) \
  ErrorDescription name (void *data)
#define DEINITIALIZE_FUNCTION_SIGNATURE(name) \
  void name ()

#define INITIALIZE_FUNCTION_DECLARATION \
  extern "C" INITIALIZE_FUNCTION_SIGNATURE(INITIALIZE_SYMBOL)
#define EXECUTE_FUNCTION_DECLARATION \
  extern "C" EXECUTE_FUNCTION_SIGNATURE(EXECUTE_SYMBOL)
#define DEINITIALIZE_FUNCTION_DECLARATION \
  extern "C" DEINITIALIZE_FUNCTION_SIGNATURE(DEINITIALIZE_SYMBOL)


struct ErrorDescription {
  //! TODO
};