#define _INITIALIZE_SYMBOL   initializePlugin
#define _EXECUTE_SYMBOL      executePlugin
#define _DEINITIALIZE_SYMBOL deinitializePlugin

#define __MAKE_STR(x) #x
#define _MAKE_STR(x) __MAKE_STR(x)

#define INITIALIZE_SYMBOL_NAME    _MAKE_STR(_INITIALIZE_SYMBOL)
#define EXECUTE_SYMBOL_NAME       _MAKE_STR(_EXECUTE_SYMBOL)
#define DEINITIALIZE_SYMBOL_NAME  _MAKE_STR(_DEINITIALIZE_SYMBOL)

#define INITIALIZE_FUNCTION_SIGNATURE(name) \
  bool name ()
#define EXECUTE_FUNCTION_SIGNATURE(name) \
  ErrorDescription name (void *data)
#define DEINITIALIZE_FUNCTION_SIGNATURE(name) \
  void name ()

#define INITIALIZE_FUNCTION_DECLARATION \
  extern "C" INITIALIZE_FUNCTION_SIGNATURE(_INITIALIZE_SYMBOL)
#define EXECUTE_FUNCTION_DECLARATION \
  extern "C" EXECUTE_FUNCTION_SIGNATURE(_EXECUTE_SYMBOL)
#define DEINITIALIZE_FUNCTION_DECLARATION \
  extern "C" DEINITIALIZE_FUNCTION_SIGNATURE(_DEINITIALIZE_SYMBOL)


struct ErrorDescription {
  //! TODO
};